%% Eigenwertproblem f?r alle Geometrien l?sen
files = {'Kreis_13.asc',...
        'Kreis_201.asc',...
        'RechteckPi_1054.asc',...
        'RechteckPi_200.asc',...
        'TrommelA_319.asc',...
        'TrommelB_321.asc',...
        'Violine_508.asc',...
        'Violine_65.asc' };
  for n = 1:length(files)
      fem_solve_grid(['Finite_Elemente/',files{n}],1);
  end
  
%% L?sungen der Rechtecke mit FEM Ergebnissen vergleichen

solR200 = fem_solve_grid('Finite_Elemente/RechteckPi_200.asc',0);
solR1054 = fem_solve_grid('Finite_Elemente/RechteckPi_1054.asc',0);

